name: Deploy to Hostinger

on:
  push:
    branches:
      - main  # Change this to your default branch if different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add known_hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.KNOWN_HOSTS_ENTRY }}" >> ~/.ssh/known_hosts

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.HOSTINGER_DEPLOY_KEY }}

    - name: Deploy to Hostinger
      run: |
        ssh -p 65002 -o StrictHostKeyChecking=no u814070959@89.117.27.149 "cd /home/u814070959/public_html/bizcrm.bizmappers.com/public && git pull origin main && composer install && php artisan migrate"
